<?php

declare(strict_types=1);

return [
    'catalog' => [
        'tic-tac-toe' => [
            'title' => 'Tic-Tac-Toe',
            'type' => 'board',
            'short_description' => 'Classic 3x3 grid game. Get three in a row to win.',
            'rules_md' => "## Rules\n\n- Players take turns placing X or O on a 3x3 grid\n- First player to get 3 in a row (horizontal, vertical, or diagonal) wins\n- If all 9 squares are filled with no winner, it's a draw",
            'options_json' => ['difficulty' => 'easy', 'ai_enabled' => true],
            'motif' => 'tictactoe',
            'livewire_component' => 'games.tic-tac-toe',
            'supports_opponent_choice' => true,
            'supports_player_symbol' => true,
            'pace' => 'quiet',
            'best_for' => 'A short, gentle break.',
            'relaxing_pick' => true,
        ],
        'connect-4' => [
            'title' => 'Connect 4',
            'type' => 'board',
            'short_description' => 'Drop pieces to connect four in a row.',
            'rules_md' => "## Rules\n\n- Take turns dropping pieces into columns\n- First player to get 4 in a row (horizontal, vertical, or diagonal) wins",
            'options_json' => ['columns' => 7, 'rows' => 6],
            'motif' => 'connect4',
            'livewire_component' => 'games.connect4',
            'supports_opponent_choice' => true,
            'pace' => 'steady',
            'best_for' => 'A little focus without much setup.',
        ],
        'sudoku' => [
            'title' => 'Sudoku',
            'type' => 'puzzle',
            'short_description' => 'Fill the 9x9 grid with digits so each column, row, and 3x3 section contains 1-9.',
            'rules_md' => "## Rules\n\n- Fill the grid so that every row, column, and 3x3 box contains the numbers 1 through 9\n- Each number can only appear once per row, column, and box\n- Use logic and deduction to solve the puzzle",
            'options_json' => ['difficulty' => 'medium', 'hints_enabled' => true],
            'motif' => 'sudoku',
            'livewire_component' => 'games.sudoku',
            'pace' => 'quiet',
            'best_for' => 'Settling in for a longer quiet sit.',
            'relaxing_pick' => true,
        ],
        'chess' => [
            'title' => 'Chess',
            'type' => 'board',
            'short_description' => 'Classic strategy board game.',
            'rules_md' => "## Rules\n\n- Move pieces according to their rules\n- Capture the opponent's king to win",
            'options_json' => ['time_control' => 'unlimited'],
            'motif' => 'chess',
            'livewire_component' => 'games.chess',
            'supports_opponent_choice' => true,
            'pace' => 'steady',
            'best_for' => 'A thoughtful session with room to think.',
        ],
        'checkers' => [
            'title' => 'Checkers',
            'type' => 'board',
            'short_description' => 'Jump your way to victory.',
            'rules_md' => "## Rules\n\n- Move diagonally and jump opponent pieces\n- Reach the opposite end to king your piece",
            'options_json' => ['board_size' => '8x8'],
            'motif' => 'checkers',
            'livewire_component' => 'games.checkers',
            'supports_opponent_choice' => true,
            'pace' => 'steady',
            'best_for' => 'Simple rules and an easy rhythm.',
        ],
        'minesweeper' => [
            'title' => 'Minesweeper',
            'type' => 'puzzle',
            'short_description' => 'Clear the board without detonating any mines. Use clues to deduce safe squares.',
            'rules_md' => "## Rules\n\n- Click squares to reveal them\n- Numbers indicate how many mines are adjacent\n- Right-click to flag suspected mines\n- Clear all non-mine squares to win",
            'options_json' => ['grid_size' => '10x10', 'mine_count' => 15],
            'motif' => 'minesweeper',
            'livewire_component' => 'games.minesweeper',
            'pace' => 'steady',
            'best_for' => 'A quiet puzzle with a bit more tension.',
        ],
        'snake' => [
            'title' => 'Snake',
            'type' => 'arcade',
            'short_description' => 'Guide the snake to eat food and grow longer.',
            'rules_md' => "## Rules\n\n- Control the snake with arrow keys\n- Eat food to grow longer\n- Don't hit walls or yourself",
            'options_json' => ['speed' => 'normal'],
            'motif' => 'snake',
            'livewire_component' => 'games.snake',
            'pace' => 'lively',
            'best_for' => 'When you want something a little more awake.',
        ],
        'twenty-forty-eight' => [
            'title' => '2048',
            'type' => 'puzzle',
            'short_description' => 'Combine tiles to reach 2048.',
            'rules_md' => "## Rules\n\n- Use arrow keys to slide tiles\n- Tiles with the same number merge when they touch\n- Try to create a 2048 tile",
            'options_json' => ['grid_size' => '4x4'],
            'motif' => '2048',
            'livewire_component' => 'games.twenty-forty-eight',
            'pace' => 'quiet',
            'best_for' => 'A calm loop you can slip into quickly.',
            'relaxing_pick' => true,
        ],
        'letter-walker' => [
            'title' => 'Letter Walker',
            'type' => 'word',
            'short_description' => 'Slide rows and columns to find hidden words in this daily puzzle game.',
            'rules_md' => "## Rules\n\n- Click and drag to select letters to form words\n- Click the arrow buttons to shift rows and columns\n- Find as many words as possible with limited moves\n- Words must be at least 3 letters long",
            'options_json' => ['grid_size' => '8x8', 'dictionary_enabled' => true],
            'motif' => 'board',
            'theme' => 'standalone',
            'show_view' => 'games.letter-walker',
            'play_view' => 'games.letter-walker',
            'layout' => 'layouts.blank',
            'redirect_play_to_show' => true,
            'pace' => 'steady',
            'best_for' => 'A thoughtful word puzzle with a daily rhythm.',
        ],
    ],
];
