<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Letter Walker - Ursa Minor</title>
        <link rel="stylesheet" href="{{ asset('assets/letter-walker/styles.css') }}" />

        @if(auth()->check())
            <meta name="user-authenticated" content="true">
            <meta name="csrf-token" content="{{ csrf_token() }}">
        @endif
    </head>
    <body>
        <div class="container">
            <header>
                <div class="header-top">
                    <a href="{{ route('games.index') }}" class="back-link">&larr; Back to Games</a>
                    <h1>Letter Walker</h1>
                </div>
                <div class="game-info">
                    <div class="score-display">
                        Score: <span id="score">0</span>
                    </div>
                    <div class="moves-display">
                        Moves: <span id="moves">0</span>
                    </div>
                    <div class="daily-info">
                        <span id="date-display"></span>
                        <span class="puzzle-num">Puzzle <span id="puzzle-num">1</span></span>
                    </div>
                    <div class="dict-loading" id="dict-loading">
                        <span class="loading-dot"></span>
                        Loading dictionary...
                    </div>
                </div>
            </header>

            <div class="game-controls">
                <button id="help-btn" class="btn secondary-btn" title="How to play">
                    ?
                </button>
                <button id="new-puzzle-btn" class="btn secondary-btn">
                    New Puzzle
                </button>
                <button id="share-btn" class="btn secondary-btn">
                    Share Results
                </button>
            </div>

            <div class="game-board-wrapper">
                <!-- Top column shift buttons -->
                <div class="top-controls">
                    <div class="spacer"></div>
                    <div class="col-controls">
                        <button class="col-btn up" data-col="0">&#9650;</button>
                        <button class="col-btn up" data-col="1">&#9650;</button>
                        <button class="col-btn up" data-col="2">&#9650;</button>
                        <button class="col-btn up" data-col="3">&#9650;</button>
                        <button class="col-btn up" data-col="4">&#9650;</button>
                        <button class="col-btn up" data-col="5">&#9650;</button>
                        <button class="col-btn up" data-col="6">&#9650;</button>
                        <button class="col-btn up" data-col="7">&#9650;</button>
                    </div>
                    <div class="spacer"></div>
                </div>

                <div class="middle-section">
                    <!-- Left row shift buttons -->
                    <div class="left-controls">
                        <button class="row-btn left" data-row="0">&#9664;</button>
                        <button class="row-btn left" data-row="1">&#9664;</button>
                        <button class="row-btn left" data-row="2">&#9664;</button>
                        <button class="row-btn left" data-row="3">&#9664;</button>
                        <button class="row-btn left" data-row="4">&#9664;</button>
                        <button class="row-btn left" data-row="5">&#9664;</button>
                        <button class="row-btn left" data-row="6">&#9664;</button>
                        <button class="row-btn left" data-row="7">&#9664;</button>
                    </div>

                    <!-- Main grid -->
                    <div class="grid-container" id="grid">
                        <!-- Grid cells will be generated by JavaScript -->
                    </div>

                    <!-- Right row shift buttons -->
                    <div class="right-controls">
                        <button class="row-btn right" data-row="0">&#9654;</button>
                        <button class="row-btn right" data-row="1">&#9654;</button>
                        <button class="row-btn right" data-row="2">&#9654;</button>
                        <button class="row-btn right" data-row="3">&#9654;</button>
                        <button class="row-btn right" data-row="4">&#9654;</button>
                        <button class="row-btn right" data-row="5">&#9654;</button>
                        <button class="row-btn right" data-row="6">&#9654;</button>
                        <button class="row-btn right" data-row="7">&#9654;</button>
                    </div>
                </div>

                <!-- Bottom column shift buttons -->
                <div class="bottom-controls">
                    <div class="spacer"></div>
                    <div class="col-controls">
                        <button class="col-btn down" data-col="0">&#9660;</button>
                        <button class="col-btn down" data-col="1">&#9660;</button>
                        <button class="col-btn down" data-col="2">&#9660;</button>
                        <button class="col-btn down" data-col="3">&#9660;</button>
                        <button class="col-btn down" data-col="4">&#9660;</button>
                        <button class="col-btn down" data-col="5">&#9660;</button>
                        <button class="col-btn down" data-col="6">&#9660;</button>
                        <button class="col-btn down" data-col="7">&#9660;</button>
                    </div>
                    <div class="spacer"></div>
                </div>
            </div>

            <div class="selection-area">
                <div class="selected-word-display">
                    <span id="selected-word"></span>
                </div>
                <button id="submit-btn" class="btn primary-btn" disabled>
                    Submit Word
                </button>
                <button id="clear-btn" class="btn secondary-btn">Clear</button>
            </div>

            <div class="found-words">
                <h3>Found Words</h3>
                <div id="found-words-list"></div>
            </div>

            <div id="message" class="message"></div>

            <!-- Help Modal -->
            <div id="help-modal" class="modal hidden">
                <div class="modal-content">
                    <h2>How to Play</h2>
                    <div class="help-instructions">
                        <p>Slide the rows and columns using the arrow buttons to rearrange the letters.</p>
                        <p>Click and drag to select letters that spell a word.</p>
                        <p>Submit your word and earn points for each valid word found.</p>
                    </div>
                    <div class="modal-buttons">
                        <button id="close-help-btn" class="btn primary-btn">Got it!</button>
                    </div>
                </div>
            </div>

            <!-- Arcade-style name entry modal -->
            <div id="name-modal" class="modal hidden">
                <div class="modal-content">
                    <h2>Game Over!</h2>
                    <p>Score: <span id="final-score"></span></p>
                    <p>Enter your name for the leaderboard:</p>
                    <input type="text" id="player-name" maxlength="50" placeholder="Your Name" />
                    <div class="modal-buttons">
                        <button id="save-name-btn" class="btn primary-btn">Save Score</button>
                        <button id="cancel-name-btn" class="btn secondary-btn">Cancel</button>
                    </div>
                </div>
            </div>

            <footer style="margin-top: 30px; text-align: center; color: #666; font-size: 0.9em;">
                Game concept by <strong>Luke Walker</strong>
            </footer>
        </div>

        <script src="{{ asset('assets/letter-walker/script.js') }}"></script>
    </body>
</html>
