<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, target-densitydpi=160dpi, initial-scale=1.0, maximum-scale=1, user-scalable=no, minimal-ui" />
        <title>Letter Walker - Ursa Minor</title>
        <link rel="stylesheet" href="{{ asset('assets/letter-walker/styles.css') }}" />

        @if(auth()->check())
            <meta name="user-authenticated" content="true">
            <meta name="csrf-token" content="{{ csrf_token() }}">
        @endif
    </head>
    <body>
        <div class="container">
            <!-- Header -->
            <header>
                <div class="header-top">
                    <a href="{{ route('games.index') }}" class="back-link">&larr; Back</a>
                    <h1>Letter Walker</h1>
                    <button id="theme-toggle" class="theme-btn" title="Toggle Theme">
                        <span class="sun-icon">☀</span>
                        <span class="moon-icon">☾</span>
                    </button>
                </div>
                <div class="game-info">
                    <div class="info-card score-card">
                        <span class="label">Score</span>
                        <span id="score">0</span>
                    </div>
                    <div class="info-card moves-card">
                        <span class="label">Moves</span>
                        <span id="moves">0</span>
                    </div>
                    <div class="puzzle-meta">
                        <div id="date-display"></div>
                        <div class="puzzle-tag">#<span id="puzzle-num">1</span></div>
                    </div>
                    <div class="dict-loading" id="dict-loading">
                        <div class="spinner"></div>
                        <span>Loading</span>
                    </div>
                </div>
            </header>

            <!-- Game Controls -->
            <div class="game-controls">
                <button id="help-btn" class="btn-icon" title="How to play">?</button>
                <button id="new-puzzle-btn" class="btn secondary">New Puzzle</button>
                <button id="share-btn" class="btn secondary">Share</button>
            </div>

            <!-- Game Board -->
            <div class="game-wrapper">
                <div class="board-layout">
                    <!-- Top Controls -->
                    <div class="controls-row top">
                        <div class="col-controls">
                            @for ($i = 0; $i < 8; $i++)
                                <button class="col-btn up" data-col="{{ $i }}" title="Shift column {{ $i+1 }} up">&#9650;</button>
                            @endfor
                        </div>
                    </div>

                    <!-- Middle Section -->
                    <div class="board-middle">
                        <div class="row-controls left">
                            @for ($i = 0; $i < 8; $i++)
                                <button class="row-btn left" data-row="{{ $i }}" title="Shift row {{ $i+1 }} left">&#9664;</button>
                            @endfor
                        </div>

                        <div class="grid-container" id="grid">
                            <!-- Grid cells generated by JS -->
                        </div>

                        <div class="row-controls right">
                            @for ($i = 0; $i < 8; $i++)
                                <button class="row-btn right" data-row="{{ $i }}" title="Shift row {{ $i+1 }} right">&#9654;</button>
                            @endfor
                        </div>
                    </div>

                    <!-- Bottom Controls -->
                    <div class="controls-row bottom">
                        <div class="col-controls">
                            @for ($i = 0; $i < 8; $i++)
                                <button class="col-btn down" data-col="{{ $i }}" title="Shift column {{ $i+1 }} down">&#9660;</button>
                            @endfor
                        </div>
                    </div>
                </div>
            </div>

            <!-- Selection Area -->
            <div class="selection-area">
                <div class="selected-word-container">
                    <span id="selected-word"></span>
                </div>
                <div class="action-buttons">
                    <button id="submit-btn" class="btn primary" disabled>Submit Word</button>
                    <button id="clear-btn" class="btn secondary">Clear</button>
                </div>
            </div>

            <!-- Found Words -->
            <div class="found-words-container">
                <h3>Found Words</h3>
                <div id="found-words-list"></div>
            </div>

            <footer>
                Game concept by <strong>Luke Walker</strong>
            </footer>
        </div>

        <div id="message" class="toast"></div>

        <!-- Modals -->
        <div id="help-modal" class="modal hidden">
            <div class="modal-overlay"></div>
            <div class="modal-content">
                <h2>How to Play</h2>
                <div class="help-scroll">
                    <p><strong>Rearrange:</strong> Slide rows and columns using the arrow buttons. Each shift adds a move.</p>
                    <p><strong>Select:</strong> Click and drag (or touch and drag) to select letters that spell a word (3-8 letters).</p>
                    <p><strong>Score:</strong> Submit your word to end the game. Longer words and fewer moves mean higher scores!</p>
                    <div class="help-tips">
                        <div class="tip"><span>☀</span> Shifts hide the outgoing letter and reveal a new one.</div>
                    </div>
                </div>
                <button id="close-help-btn" class="btn primary full-width">Start Playing</button>
            </div>
        </div>

        <div id="name-modal" class="modal hidden">
            <div class="modal-overlay"></div>
            <div class="modal-content">
                <h2>High Score!</h2>
                <div class="final-score-display">
                    <span id="final-score">0</span>
                    <span class="score-label">Points</span>
                </div>
                <p>Enter your name for the leaderboard:</p>
                <input type="text" id="player-name" maxlength="20" placeholder="Player Name" autofocus />
                <div class="modal-actions">
                    <button id="save-name-btn" class="btn primary">Save</button>
                    <button id="cancel-name-btn" class="btn secondary">Skip</button>
                </div>
            </div>
        </div>

        <script src="{{ asset('assets/letter-walker/script.js') }}"></script>
    </body>
</html>
