<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, target-densitydpi=160dpi, initial-scale=1.0, maximum-scale=1, user-scalable=no, minimal-ui" />
        <title>Letter Walker - Ursa Minor</title>
        <link rel="stylesheet" href="{{ asset('assets/letter-walker/styles.css') }}" />

        <meta name="csrf-token" content="{{ csrf_token() }}">
        @if(auth()->check())
            <meta name="user-authenticated" content="true">
        @endif
    </head>
    <body>
        <div class="wrap">
            <header class="header-strip">
                <a href="{{ route('games.index') }}" class="back-link">Back</a>
                <div class="header-center">
                    <h1 class="title">Letter Walker</h1>
                    <p class="meta"><span id="date-display"></span> &nbsp;#<span id="puzzle-num">1</span></p>
                </div>
                <div class="header-right">
                    <button id="theme-toggle" class="icon-btn" type="button" title="Toggle light/dark">Theme</button>
                    <button id="help-btn" class="icon-btn" type="button" title="How to play">?</button>
                </div>
            </header>

            <div class="dict-loading" id="dict-loading" aria-hidden="true">
                <span class="spinner"></span>
                <span>Loading</span>
            </div>

            <p class="instruction" id="instruction-text">Slide rows and columns, then select a word in a straight line.</p>

            <div class="board-outer">
                <div class="controls-row top">
                    <div class="col-controls">
                        @for ($i = 0; $i < 8; $i++)
                            <button class="col-btn up" type="button" data-col="{{ $i }}" title="Shift column {{ $i+1 }} up" aria-label="Shift column {{ $i+1 }} up">&#9650;</button>
                        @endfor
                    </div>
                </div>
                <div class="board-middle">
                    <div class="row-controls left">
                        @for ($i = 0; $i < 8; $i++)
                            <button class="row-btn left" type="button" data-row="{{ $i }}" title="Shift row {{ $i+1 }} left" aria-label="Shift row {{ $i+1 }} left">&#9664;</button>
                        @endfor
                    </div>
                    <div class="grid-container" id="grid" role="grid" aria-label="8 by 8 letter grid">
                        <!-- Grid cells generated by JS -->
                    </div>
                    <div class="row-controls right">
                        @for ($i = 0; $i < 8; $i++)
                            <button class="row-btn right" type="button" data-row="{{ $i }}" title="Shift row {{ $i+1 }} right" aria-label="Shift row {{ $i+1 }} right">&#9654;</button>
                        @endfor
                    </div>
                </div>
                <div class="controls-row bottom">
                    <div class="col-controls">
                        @for ($i = 0; $i < 8; $i++)
                            <button class="col-btn down" type="button" data-col="{{ $i }}" title="Shift column {{ $i+1 }} down" aria-label="Shift column {{ $i+1 }} down">&#9660;</button>
                        @endfor
                    </div>
                </div>
            </div>

            <section class="selection-block">
                <div class="selected-word-container" aria-live="polite">
                    <span id="selected-word" class="selected-word"></span>
                </div>
                <div class="action-btns">
                    <button id="new-puzzle-btn" type="button" class="btn btn-secondary">New Puzzle</button>
                    <button id="clear-btn" type="button" class="btn btn-secondary" disabled>Clear</button>
                    <button id="submit-btn" type="button" class="btn btn-primary" disabled>Submit</button>
                    <button id="share-btn" type="button" class="btn btn-secondary">Share</button>
                </div>
            </section>

            <section class="found-section">
                <h4 class="found-label">Found words</h4>
                <div id="found-words-list" class="found-pills"></div>
            </section>

            <section class="leaderboard" id="leaderboard">
                <h4 class="leaderboard-title">Today&#039;s Top Scores</h4>
                <div id="leaderboard-body">
                    <p class="leaderboard-empty">No scores yet today. Be the first!</p>
                </div>
            </section>

            <div id="message" class="message" role="status" aria-live="polite"></div>

            <!-- Hidden for stats/script; not shown in header -->
            <div class="sr-only" aria-hidden="true">
                <span id="score">0</span>
                <span id="moves">0</span>
            </div>

            <div id="help-modal" class="modal hidden" aria-modal="true" aria-labelledby="help-modal-title">
                <div class="modal-content">
                    <h2 id="help-modal-title">How to Play</h2>
                    <div class="help-instructions">
                        <p>Slide the rows and columns using the arrow buttons to rearrange the letters.</p>
                        <p>Click and drag to select letters that spell a word.</p>
                        <p>Submit your word when you find a valid word (3–8 letters). Words must be in a straight line (horizontal or vertical).</p>
                        <h3>Scoring</h3>
                        <ul>
                            <li>10 points per letter (e.g. 4 letters = 40 points).</li>
                            <li>Minus 1 point per move. A move = shifting one row or column; shifting the same row or column multiple times counts as 1 move.</li>
                            <li>8-letter words get a 2&times; multiplier.</li>
                            <li>Final score = (letters &times; 10 &minus; moves) &times; multiplier, never below zero.</li>
                        </ul>
                    </div>
                    <div class="modal-buttons">
                        <button id="close-help-btn" type="button" class="btn primary-btn">Got it!</button>
                    </div>
                </div>
            </div>

            <div id="name-modal" class="modal hidden" aria-modal="true" aria-labelledby="name-modal-title">
                <div class="modal-content">
                    <h2 id="name-modal-title">Game Over!</h2>
                    <p>Score: <span id="final-score"></span></p>
                    <p>Enter your name for the leaderboard:</p>
                    <input type="text" id="player-name" maxlength="50" placeholder="Your Name" aria-label="Your name" />
                    <div class="modal-buttons">
                        <button id="save-name-btn" type="button" class="btn primary-btn">Save Score</button>
                        <button id="cancel-name-btn" type="button" class="btn secondary-btn">Cancel</button>
                    </div>
                </div>
            </div>

            <footer class="letter-walker-footer">
                Game concept by Luke Walker
            </footer>
        </div>

        <script src="{{ asset('assets/letter-walker/script.js') }}"></script>
    </body>
</html>
