name: Railway Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ursaminor:test .

      - name: Verify PHP installation
        run: docker run --rm ursaminor:test php -v

      - name: Verify Composer autoload
        run: docker run --rm -e APP_KEY=base64:FAKEKEY12345678901234567890123456789012= ursaminor:test php artisan --version

      - name: Check built assets exist
        run: docker run --rm ursaminor:test ls -la /var/www/html/public/build

      - name: Verify vendor directory
        run: docker run --rm ursaminor:test ls -la /var/www/html/vendor

      - name: Check permissions
        run: docker run --rm ursaminor:test ls -ld /var/www/html/storage /var/www/html/bootstrap/cache

